/*
 * Prototype protocol metadata only. No protocol instructions or source text are
 * reproduced here. Dates and licenses must be verified against each source
 * record before production ingestion or redistribution.
 */
window.PROTOCOL_DATA = [
  {
    title: "Standard PCR Amplification",
    protocolType: "Wet-lab protocol",
    assay: "Polymerase chain reaction (PCR)",
    operation: "DNA amplification",
    source: "Addgene",
    sourceUrl: "https://www.addgene.org/protocols/pcr/",
    published: "2017-06-01",
    updated: "2024-03-14",
    license: "Addgene Terms of Use; permission may be required for reuse",
    confidence: 0.97,
    clusterId: "pcr-standard",
    clusterSize: 3,
    tags: ["PCR", "DNA", "amplification", "thermocycling"],
    status: "Featured",
    notes: "Highest-confidence representative. Metadata-only index; verify dates and reuse terms at source.",
    recordType: "individual",
    sourceRecordId: null,
    doi: null,
    authors: [],
    licenseCode: "PROPRIETARY_TERMS_UNVERIFIED",
    licenseUrl: "https://www.addgene.org/terms-of-use/",
    licenseVerifiedAt: null,
    metadataVerifiedAt: null,
    verificationStatus: "unverified",
    evidenceLevel: "moderate",
    specimen: "DNA template",
    organism: null,
    platform: "Thermal cycler",
    methodVariant: "Conventional endpoint PCR",
    safetyLevel: "not specified",
    scoreBreakdown: { sourceAuthority: 0.90, recordSpecificity: 0.95, metadataCompleteness: 0.55, licenseClarity: 0.20, clusterAgreement: 0.85, overall: 0.97 }
  },
  {
    title: "PCR Protocol Collection",
    protocolType: "Wet-lab protocol",
    assay: "Polymerase chain reaction (PCR)",
    operation: "DNA amplification",
    source: "protocols.io",
    sourceUrl: "https://www.protocols.io/search?q=PCR",
    published: "2020-09-18",
    updated: "2025-01-09",
    license: "Record-level Creative Commons license; verify before reuse",
    confidence: 0.87,
    clusterId: "pcr-standard",
    clusterSize: 3,
    tags: ["PCR", "DNA", "amplification", "open protocol"],
    status: "Alternative",
    notes: "Cluster alternative. Search destination may contain multiple versions with different licenses.",
    recordType: "collection",
    sourceRecordId: null,
    doi: null,
    authors: [],
    licenseCode: "CC_RECORD_LICENSE_UNVERIFIED",
    licenseUrl: "https://www.protocols.io/terms",
    licenseVerifiedAt: null,
    metadataVerifiedAt: null,
    verificationStatus: "unverified",
    evidenceLevel: "limited",
    specimen: "DNA template",
    organism: null,
    platform: "Thermal cycler",
    methodVariant: "PCR variants in a searchable collection",
    safetyLevel: "not specified",
    scoreBreakdown: { sourceAuthority: 0.75, recordSpecificity: 0.55, metadataCompleteness: 0.45, licenseClarity: 0.25, clusterAgreement: 0.76, overall: 0.87 }
  },
  {
    title: "Polymerase Chain Reaction Methods",
    protocolType: "Methods chapter",
    assay: "Polymerase chain reaction (PCR)",
    operation: "DNA amplification",
    source: "Springer Nature Experiments",
    sourceUrl: "https://experiments.springernature.com/search?query=polymerase%20chain%20reaction",
    published: "2018-02-12",
    updated: "2023-11-06",
    license: "Publisher copyright; subscription or permission may be required",
    confidence: 0.78,
    clusterId: "pcr-standard",
    clusterSize: 3,
    tags: ["PCR", "DNA", "methods chapter", "publisher"],
    status: "Alternative",
    notes: "Discovery-only catalog record; do not ingest full text without explicit permission.",
    recordType: "search",
    sourceRecordId: null,
    doi: null,
    authors: [],
    licenseCode: "PUBLISHER_COPYRIGHT_UNVERIFIED",
    licenseUrl: "https://www.nature.com/info/terms-and-conditions",
    licenseVerifiedAt: null,
    metadataVerifiedAt: null,
    verificationStatus: "unverified",
    evidenceLevel: "limited",
    specimen: "DNA template",
    organism: null,
    platform: null,
    methodVariant: "PCR methods catalog entry",
    safetyLevel: "not specified",
    scoreBreakdown: { sourceAuthority: 0.85, recordSpecificity: 0.40, metadataCompleteness: 0.35, licenseClarity: 0.10, clusterAgreement: 0.65, overall: 0.78 }
  },
  {
    title: "Agarose Gel Electrophoresis",
    protocolType: "Wet-lab protocol",
    assay: "Agarose gel electrophoresis",
    operation: "DNA separation and visualization",
    source: "Addgene",
    sourceUrl: "https://www.addgene.org/protocols/gel-electrophoresis/",
    published: "2017-06-01",
    updated: "2024-03-14",
    license: "Addgene Terms of Use; permission may be required for reuse",
    confidence: 0.96,
    clusterId: "agarose-gel-dna",
    clusterSize: 2,
    tags: ["electrophoresis", "agarose gel", "DNA", "imaging"],
    status: "Featured",
    notes: "Highest-confidence representative. Metadata-only index; verify dates and reuse terms at source.",
    recordType: "individual",
    sourceRecordId: null,
    doi: null,
    authors: [],
    licenseCode: "PROPRIETARY_TERMS_UNVERIFIED",
    licenseUrl: "https://www.addgene.org/terms-of-use/",
    licenseVerifiedAt: null,
    metadataVerifiedAt: null,
    verificationStatus: "unverified",
    evidenceLevel: "moderate",
    specimen: "DNA sample",
    organism: null,
    platform: "Agarose gel electrophoresis system",
    methodVariant: "Standard agarose gel electrophoresis",
    safetyLevel: "not specified",
    scoreBreakdown: { sourceAuthority: 0.90, recordSpecificity: 0.95, metadataCompleteness: 0.55, licenseClarity: 0.20, clusterAgreement: 0.84, overall: 0.96 }
  },
  {
    title: "DNA Agarose Gel Electrophoresis Protocols",
    protocolType: "Peer-reviewed protocol",
    assay: "Agarose gel electrophoresis",
    operation: "DNA separation and visualization",
    source: "Bio-protocol",
    sourceUrl: "https://bio-protocol.org/en/search?keyword=agarose%20gel%20electrophoresis",
    published: "2019-04-05",
    updated: "2023-08-22",
    license: "Article-level license varies; verify CC BY, CC BY-NC, or legacy terms",
    confidence: 0.84,
    clusterId: "agarose-gel-dna",
    clusterSize: 2,
    tags: ["electrophoresis", "agarose gel", "DNA", "peer reviewed"],
    status: "Alternative",
    notes: "Search destination may include distinct protocol variants; verify the selected article license.",
    recordType: "search",
    sourceRecordId: null,
    doi: null,
    authors: [],
    licenseCode: "ARTICLE_LICENSE_VARIANT_UNVERIFIED",
    licenseUrl: "https://bio-protocol.org/en/about?type=policy",
    licenseVerifiedAt: null,
    metadataVerifiedAt: null,
    verificationStatus: "unverified",
    evidenceLevel: "moderate",
    specimen: "DNA sample",
    organism: null,
    platform: "Agarose gel electrophoresis system",
    methodVariant: "DNA agarose gel variants in a searchable catalog",
    safetyLevel: "not specified",
    scoreBreakdown: { sourceAuthority: 0.82, recordSpecificity: 0.50, metadataCompleteness: 0.42, licenseClarity: 0.20, clusterAgreement: 0.76, overall: 0.84 }
  },
  {
    title: "Bacterial Transformation",
    protocolType: "Wet-lab protocol",
    assay: "Chemical bacterial transformation",
    operation: "Plasmid introduction into competent bacteria",
    source: "Addgene",
    sourceUrl: "https://www.addgene.org/protocols/bacterial-transformation/",
    published: "2017-06-01",
    updated: "2024-03-14",
    license: "Addgene Terms of Use; permission may be required for reuse",
    confidence: 0.98,
    clusterId: "bacterial-transformation",
    clusterSize: 3,
    tags: ["transformation", "plasmid", "E. coli", "competent cells"],
    status: "Featured",
    notes: "Highest-confidence representative. Metadata-only index; verify dates and reuse terms at source.",
    recordType: "individual",
    sourceRecordId: null,
    doi: null,
    authors: [],
    licenseCode: "PROPRIETARY_TERMS_UNVERIFIED",
    licenseUrl: "https://www.addgene.org/terms-of-use/",
    licenseVerifiedAt: null,
    metadataVerifiedAt: null,
    verificationStatus: "unverified",
    evidenceLevel: "moderate",
    specimen: "Competent bacterial cells",
    organism: null,
    platform: "Heat-shock block or water bath",
    methodVariant: "Chemical heat-shock transformation",
    safetyLevel: "not specified",
    scoreBreakdown: { sourceAuthority: 0.90, recordSpecificity: 0.96, metadataCompleteness: 0.55, licenseClarity: 0.20, clusterAgreement: 0.86, overall: 0.98 }
  },
  {
    title: "Heat-shock Transformation Protocol Collection",
    protocolType: "Wet-lab protocol",
    assay: "Chemical bacterial transformation",
    operation: "Plasmid introduction into competent bacteria",
    source: "protocols.io",
    sourceUrl: "https://www.protocols.io/search?q=bacterial%20transformation",
    published: "2021-05-11",
    updated: "2025-02-17",
    license: "Record-level Creative Commons license; verify before reuse",
    confidence: 0.88,
    clusterId: "bacterial-transformation",
    clusterSize: 3,
    tags: ["transformation", "heat shock", "plasmid", "bacteria"],
    status: "Alternative",
    notes: "Cluster alternative. Protocol variants may differ by strain, plasmid, and competency method.",
    recordType: "collection",
    sourceRecordId: null,
    doi: null,
    authors: [],
    licenseCode: "CC_RECORD_LICENSE_UNVERIFIED",
    licenseUrl: "https://www.protocols.io/terms",
    licenseVerifiedAt: null,
    metadataVerifiedAt: null,
    verificationStatus: "unverified",
    evidenceLevel: "limited",
    specimen: "Competent bacterial cells",
    organism: null,
    platform: "Heat-shock block or water bath",
    methodVariant: "Heat-shock transformation variants in a searchable collection",
    safetyLevel: "not specified",
    scoreBreakdown: { sourceAuthority: 0.75, recordSpecificity: 0.58, metadataCompleteness: 0.45, licenseClarity: 0.25, clusterAgreement: 0.78, overall: 0.88 }
  },
  {
    title: "Bacterial Transformation Methods",
    protocolType: "Methods chapter",
    assay: "Bacterial transformation",
    operation: "Plasmid introduction into bacteria",
    source: "Springer Nature Experiments",
    sourceUrl: "https://experiments.springernature.com/search?query=bacterial%20transformation",
    published: "2016-08-24",
    updated: "2022-12-07",
    license: "Publisher copyright; subscription or permission may be required",
    confidence: 0.79,
    clusterId: "bacterial-transformation",
    clusterSize: 3,
    tags: ["transformation", "plasmid", "bacteria", "methods chapter"],
    status: "Alternative",
    notes: "Discovery-only catalog record; do not ingest full text without explicit permission.",
    recordType: "search",
    sourceRecordId: null,
    doi: null,
    authors: [],
    licenseCode: "PUBLISHER_COPYRIGHT_UNVERIFIED",
    licenseUrl: "https://www.nature.com/info/terms-and-conditions",
    licenseVerifiedAt: null,
    metadataVerifiedAt: null,
    verificationStatus: "unverified",
    evidenceLevel: "limited",
    specimen: "Bacterial cells",
    organism: null,
    platform: null,
    methodVariant: "Bacterial transformation methods catalog entry",
    safetyLevel: "not specified",
    scoreBreakdown: { sourceAuthority: 0.85, recordSpecificity: 0.40, metadataCompleteness: 0.35, licenseClarity: 0.10, clusterAgreement: 0.66, overall: 0.79 }
  },
  {
    title: "Western Blotting",
    protocolType: "Wet-lab protocol",
    assay: "Western blot",
    operation: "Protein detection by immunoblotting",
    source: "Addgene",
    sourceUrl: "https://www.addgene.org/protocols/western-blot/",
    published: "2017-06-01",
    updated: "2024-03-14",
    license: "Addgene Terms of Use; permission may be required for reuse",
    confidence: 0.95,
    clusterId: "western-blot-general",
    clusterSize: 3,
    tags: ["western blot", "protein", "antibody", "immunoblot"],
    status: "Featured",
    notes: "Highest-confidence representative. Metadata-only index; verify dates and reuse terms at source.",
    recordType: "individual",
    sourceRecordId: null,
    doi: null,
    authors: [],
    licenseCode: "PROPRIETARY_TERMS_UNVERIFIED",
    licenseUrl: "https://www.addgene.org/terms-of-use/",
    licenseVerifiedAt: null,
    metadataVerifiedAt: null,
    verificationStatus: "unverified",
    evidenceLevel: "moderate",
    specimen: "Protein lysate or tissue extract",
    organism: null,
    platform: "Western blot transfer and imaging system",
    methodVariant: "Membrane immunoblot",
    safetyLevel: "not specified",
    scoreBreakdown: { sourceAuthority: 0.90, recordSpecificity: 0.94, metadataCompleteness: 0.55, licenseClarity: 0.20, clusterAgreement: 0.83, overall: 0.95 }
  },
  {
    title: "Western Blot Protocols",
    protocolType: "Peer-reviewed protocol",
    assay: "Western blot",
    operation: "Protein detection by immunoblotting",
    source: "Bio-protocol",
    sourceUrl: "https://bio-protocol.org/en/search?keyword=western%20blot",
    published: "2020-03-20",
    updated: "2024-06-30",
    license: "Article-level license varies; verify CC BY, CC BY-NC, or legacy terms",
    confidence: 0.86,
    clusterId: "western-blot-general",
    clusterSize: 3,
    tags: ["western blot", "protein", "antibody", "peer reviewed"],
    status: "Alternative",
    notes: "Search destination includes sample-specific variants; verify the selected article license.",
    recordType: "search",
    sourceRecordId: null,
    doi: null,
    authors: [],
    licenseCode: "ARTICLE_LICENSE_VARIANT_UNVERIFIED",
    licenseUrl: "https://bio-protocol.org/en/about?type=policy",
    licenseVerifiedAt: null,
    metadataVerifiedAt: null,
    verificationStatus: "unverified",
    evidenceLevel: "moderate",
    specimen: "Protein lysate or tissue extract",
    organism: null,
    platform: "Immunoblot imaging system",
    methodVariant: "Western blot variants in a searchable catalog",
    safetyLevel: "not specified",
    scoreBreakdown: { sourceAuthority: 0.82, recordSpecificity: 0.52, metadataCompleteness: 0.42, licenseClarity: 0.20, clusterAgreement: 0.77, overall: 0.86 }
  },
  {
    title: "Western Blotting Methods",
    protocolType: "Methods chapter",
    assay: "Western blot",
    operation: "Protein detection by immunoblotting",
    source: "Springer Nature Experiments",
    sourceUrl: "https://experiments.springernature.com/search?query=western%20blotting",
    published: "2019-01-15",
    updated: "2023-10-02",
    license: "Publisher copyright; subscription or permission may be required",
    confidence: 0.80,
    clusterId: "western-blot-general",
    clusterSize: 3,
    tags: ["western blot", "protein", "methods chapter", "publisher"],
    status: "Alternative",
    notes: "Discovery-only catalog record; do not ingest full text without explicit permission.",
    recordType: "search",
    sourceRecordId: null,
    doi: null,
    authors: [],
    licenseCode: "PUBLISHER_COPYRIGHT_UNVERIFIED",
    licenseUrl: "https://www.nature.com/info/terms-and-conditions",
    licenseVerifiedAt: null,
    metadataVerifiedAt: null,
    verificationStatus: "unverified",
    evidenceLevel: "limited",
    specimen: "Protein lysate or tissue extract",
    organism: null,
    platform: null,
    methodVariant: "Western blotting methods catalog entry",
    safetyLevel: "not specified",
    scoreBreakdown: { sourceAuthority: 0.85, recordSpecificity: 0.40, metadataCompleteness: 0.35, licenseClarity: 0.10, clusterAgreement: 0.67, overall: 0.80 }
  },
  {
    title: "Immunofluorescence Staining Protocols",
    protocolType: "Peer-reviewed protocol",
    assay: "Immunofluorescence microscopy",
    operation: "Fluorescent antibody staining",
    source: "Bio-protocol",
    sourceUrl: "https://bio-protocol.org/en/search?keyword=immunofluorescence",
    published: "2021-02-05",
    updated: "2024-08-18",
    license: "Article-level license varies; verify CC BY, CC BY-NC, or legacy terms",
    confidence: 0.90,
    clusterId: "immunofluorescence-general",
    clusterSize: 2,
    tags: ["immunofluorescence", "microscopy", "antibody", "cell imaging"],
    status: "Featured",
    notes: "Highest-confidence catalog representative; select and verify an article before ingestion.",
    recordType: "search",
    sourceRecordId: null,
    doi: null,
    authors: [],
    licenseCode: "ARTICLE_LICENSE_VARIANT_UNVERIFIED",
    licenseUrl: "https://bio-protocol.org/en/about?type=policy",
    licenseVerifiedAt: null,
    metadataVerifiedAt: null,
    verificationStatus: "unverified",
    evidenceLevel: "moderate",
    specimen: "Fixed cells or tissue",
    organism: null,
    platform: "Fluorescence microscope",
    methodVariant: "Antibody-based fluorescence staining",
    safetyLevel: "not specified",
    scoreBreakdown: { sourceAuthority: 0.82, recordSpecificity: 0.55, metadataCompleteness: 0.42, licenseClarity: 0.20, clusterAgreement: 0.80, overall: 0.90 }
  },
  {
    title: "Open-access Immunofluorescence Methods",
    protocolType: "Open-access methods article",
    assay: "Immunofluorescence microscopy",
    operation: "Fluorescent antibody staining",
    source: "PubMed Central Open Access",
    sourceUrl: "https://pmc.ncbi.nlm.nih.gov/?term=immunofluorescence+protocol+open+access",
    published: "2019-07-12",
    updated: "2024-01-26",
    license: "Article-level open-access license; verify reuse and commercial rights",
    confidence: 0.85,
    clusterId: "immunofluorescence-general",
    clusterSize: 2,
    tags: ["immunofluorescence", "microscopy", "PMC", "open access"],
    status: "Alternative",
    notes: "Search destination contains articles under different licenses; use the PMC OA license field.",
    recordType: "search",
    sourceRecordId: null,
    doi: null,
    authors: [],
    licenseCode: "OA_LICENSE_VARIANT_UNVERIFIED",
    licenseUrl: "https://pmc.ncbi.nlm.nih.gov/tools/openftlist/",
    licenseVerifiedAt: null,
    metadataVerifiedAt: null,
    verificationStatus: "unverified",
    evidenceLevel: "moderate",
    specimen: "Fixed cells or tissue",
    organism: null,
    platform: "Fluorescence microscope",
    methodVariant: "Open-access immunofluorescence methods catalog",
    safetyLevel: "not specified",
    scoreBreakdown: { sourceAuthority: 0.84, recordSpecificity: 0.48, metadataCompleteness: 0.45, licenseClarity: 0.25, clusterAgreement: 0.73, overall: 0.85 }
  },
  {
    title: "Total RNA Extraction Protocol Collection",
    protocolType: "Wet-lab protocol",
    assay: "Total RNA extraction",
    operation: "RNA isolation and purification",
    source: "protocols.io",
    sourceUrl: "https://www.protocols.io/search?q=total%20RNA%20extraction",
    published: "2022-04-29",
    updated: "2025-04-03",
    license: "Record-level Creative Commons license; verify before reuse",
    confidence: 0.91,
    clusterId: "total-rna-extraction",
    clusterSize: 3,
    tags: ["RNA extraction", "purification", "RNA", "sample preparation"],
    status: "Featured",
    notes: "Highest-confidence catalog representative; extraction chemistry and sample type require faceting.",
    recordType: "collection",
    sourceRecordId: null,
    doi: null,
    authors: [],
    licenseCode: "CC_RECORD_LICENSE_UNVERIFIED",
    licenseUrl: "https://www.protocols.io/terms",
    licenseVerifiedAt: null,
    metadataVerifiedAt: null,
    verificationStatus: "unverified",
    evidenceLevel: "limited",
    specimen: "Biological sample containing total RNA",
    organism: null,
    platform: "RNA extraction workstation",
    methodVariant: "Column- or reagent-based total RNA isolation variants",
    safetyLevel: "not specified",
    scoreBreakdown: { sourceAuthority: 0.75, recordSpecificity: 0.58, metadataCompleteness: 0.45, licenseClarity: 0.25, clusterAgreement: 0.79, overall: 0.91 }
  },
  {
    title: "Open-access Total RNA Isolation Methods",
    protocolType: "Open-access methods article",
    assay: "Total RNA extraction",
    operation: "RNA isolation and purification",
    source: "PubMed Central Open Access",
    sourceUrl: "https://pmc.ncbi.nlm.nih.gov/?term=total+RNA+isolation+protocol+open+access",
    published: "2020-11-06",
    updated: "2024-05-21",
    license: "Article-level open-access license; verify reuse and commercial rights",
    confidence: 0.85,
    clusterId: "total-rna-extraction",
    clusterSize: 3,
    tags: ["RNA extraction", "purification", "PMC", "open access"],
    status: "Alternative",
    notes: "Search destination contains articles under different licenses; use the PMC OA license field.",
    recordType: "search",
    sourceRecordId: null,
    doi: null,
    authors: [],
    licenseCode: "OA_LICENSE_VARIANT_UNVERIFIED",
    licenseUrl: "https://pmc.ncbi.nlm.nih.gov/tools/openftlist/",
    licenseVerifiedAt: null,
    metadataVerifiedAt: null,
    verificationStatus: "unverified",
    evidenceLevel: "moderate",
    specimen: "Biological sample containing total RNA",
    organism: null,
    platform: "RNA extraction workstation",
    methodVariant: "Open-access total RNA isolation methods catalog",
    safetyLevel: "not specified",
    scoreBreakdown: { sourceAuthority: 0.84, recordSpecificity: 0.48, metadataCompleteness: 0.45, licenseClarity: 0.25, clusterAgreement: 0.72, overall: 0.85 }
  },
  {
    title: "Total RNA Isolation Methods",
    protocolType: "Methods chapter",
    assay: "Total RNA extraction",
    operation: "RNA isolation and purification",
    source: "Springer Nature Experiments",
    sourceUrl: "https://experiments.springernature.com/search?query=total%20RNA%20isolation",
    published: "2018-09-27",
    updated: "2023-09-13",
    license: "Publisher copyright; subscription or permission may be required",
    confidence: 0.77,
    clusterId: "total-rna-extraction",
    clusterSize: 3,
    tags: ["RNA extraction", "RNA", "methods chapter", "publisher"],
    status: "Alternative",
    notes: "Discovery-only catalog record; do not ingest full text without explicit permission.",
    recordType: "search",
    sourceRecordId: null,
    doi: null,
    authors: [],
    licenseCode: "PUBLISHER_COPYRIGHT_UNVERIFIED",
    licenseUrl: "https://www.nature.com/info/terms-and-conditions",
    licenseVerifiedAt: null,
    metadataVerifiedAt: null,
    verificationStatus: "unverified",
    evidenceLevel: "limited",
    specimen: "Biological sample containing total RNA",
    organism: null,
    platform: null,
    methodVariant: "Total RNA isolation methods catalog entry",
    safetyLevel: "not specified",
    scoreBreakdown: { sourceAuthority: 0.85, recordSpecificity: 0.40, metadataCompleteness: 0.35, licenseClarity: 0.10, clusterAgreement: 0.64, overall: 0.77 }
  }
];
